;;; autoconf.el --- Autogenerated list of installed packages.

;; Copyright (C) 2018 Evan Nagle

;; Author: Evan Nagle <evan@mantle.co>
;; URL: https://github.com/evannagle/my-emacs
;; Version: 0.0.1

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

(provide 'using)

;;; autoconf.el ends here
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   '("3b69ddebc3b1386c63e70afa0eca90d1a775c52ad144d16df932400f3afe1c30" "c83c095dd01cde64b631fb0fe5980587deec3834dc55144a6e78ff91ebc80b19" "4ee3938bc870a55681c506dcef15ead25ebbd4d43d2f1f490225e4e0385ca162" "9b59e147dbbde5e638ea1cde5ec0a358d5f269d27bd2b893a0947c4a867e14c1" "8e1601ae929030a0314aa11a8d17a74c0ed3c5b455c04921c62043ed4fc48659" "c48551a5fb7b9fc019bf3f61ebf14cf7c9cdca79bcb2a4219195371c02268f11" "f540efec38befb1a2f37e98831d9ba5b8cc495b4dea75c499dfbe7d8c594be9d" "766c5700d551f8a3bbc3be8eb4c1e3329febcb7ba572c9ee2e83cb12e18854a8" default))
 '(epg-gpg-program "/usr/local/Cellar/gnupg/2.2.3/bin/gpg")
 '(ns-alternate-modifier '(:ordinary meta :function meta :mouse meta))
 '(org-agenda-custom-commands
   '(("n" "Agenda and all TODOs"
      ((agenda "" nil)
       (alltodo "" nil))
      nil)
     ("z" "Next items on agenda "
      ((tags "URGENT"
	     ((org-agenda-overriding-header "Urgent Tasks")))
       (todo "NEXT"
	     ((org-agenda-overriding-header "Next Tasks on Agenda")))
       (agenda ""
	       ((org-deadline-warning-days 2)
		(org-agenda-span 'day)
		(org-agenda-overriding-header "Upcoming Deadlines"))))
      nil nil)))
 '(org-agenda-files
   '("/Users/evannagle/Dropbox/Apps/Beorg/learn/learn.org" "/Users/evannagle/Dropbox/Apps/Beorg/tasks.org" "/Users/evannagle/Dropbox/Apps/Beorg/agenda.org"))
 '(package-selected-packages
   '(doom-themes lua-mode editorconfig slime clojure-mode evil-lispy lispy yaml-mode prettify-symbols-mode deferred inerital-scroll typescript-mode php-doc flex-mode bison-mode evil-commentary evil-surround fzf jinja2-mode evil-smartparens smartparens hydra org-mu4e evil-magit flx-ido flx evil-collection mu4e pass "ob-sh" ob-sh coffee-mode elisp-def evil-escape exec-path-from-shell whole-line-or-region evil web-mode php-mode less-css-mode gitignore-mode rainbow-delimiters projectile org-bullets magit helpful expand-region diminish counsel company ag ace-window benchmark-init use-package))
 '(safe-local-variable-values
   '((eval local-set-key
	   (kbd "<f11>")
	   '(lambda nil
	      (interactive)
	      (org-babel-goto-named-src-block "make-readme")
	      (org-babel-execute-src-block)
	      (outline-hide-sublevels 1)))
     (eval progn
	   (visual-line-mode t)
	   (require 'ox-extra)
	   (ox-extras-activate
	    '(ignore-headlines))))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
