;;; data-tuck.el --- Remove Emacs data files from base folder.

;; Copyright (C) 2018 Evan Nagle

;; Author: Evan Nagle <evan@mantle.co>
;; URL: https://github.com/evannagle/my-emacs
;; Version: 0.0.1

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

(defvar my/.emacs.d/data (expand-file-name "data" user-emacs-directory))

(defvar my/autogenerated-files
  (list
   (cons 'abbrev-file-name (expand-file-name "abbrev_defs" user-emacs-directory))
   (cons 'bookmark-default-file (expand-file-name "bookmarks" user-emacs-directory))
   (cons 'recentf-save-file (expand-file-name "recentf" user-emacs-directory))
   (cons 'nsm-settings-file (expand-file-name "network-security.data" user-emacs-directory))
   (cons 'projectile-known-projects-file (expand-file-name "projectile-bookmarks.eld" user-emacs-directory))))

(dolist (file my/autogenerated-files)
  (let* ((key (car file))
	 (file (cdr file))
	 (file-name (file-name-nondirectory file))
	 (new-file-name (expand-file-name file-name my/.emacs.d/data)))
    (set key new-file-name)))

(provide 'my/data-tuck)

;;; tuck.el ends here
